language: node_js

node_js:
  - "10.15.3"

before_script:
  - "cd review-notifications"
  - "yarn"

script:
  - "yarn lint"
  - "yarn test"

notifications:
  slack:
    rooms:
      - innoprojectsummer2019:PAHJCBRPZFNF5g0vfXap0Jpq
    on_success: never
